# exclude everything by default to limit context size and cache miss
*
# module definition
!go.*
# internal dependencies
!cannon/
!op-alt-da/
!fd-node/
!op-preimage/
!fd-program/
!fd-service/
!fd-supervisor/

**/bin
**/testdata
**/tests
