FROM debian:bookworm-20240812-slim
ENTRYPOINT ["/dn-deployer"]
COPY dn-deployer /dn-deployer

# Install ca-certificates so that HTTPS requests work
RUN apt-get update && apt-get install -y ca-certificates

# Symlink onto the PATH
RUN ln -s /dn-deployer /usr/local/bin/dn-deployer
