FROM debian:bookworm-20240812-slim
ENTRYPOINT ["/fd-deployer"]
COPY fd-deployer /fd-deployer

# Install ca-certificates so that HTTPS requests work
RUN apt-get update && apt-get install -y ca-certificates

# Symlink onto the PATH
RUN ln -s /fd-deployer /usr/local/bin/fd-deployer
